/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutPicker: typeof import('nutui-uniapp/components/picker/picker.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
  }
}
